# Generated by Django 4.1.1 on 2022-09-24 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dia_semanamodel',
            name='modified_in',
            field=models.DateTimeField(auto_now=True, verbose_name='Modificado em'),
        ),
    ]
